name: Selenium CI

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main

  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:
    inputs:
      suite:
        description: Test suite
        required: true
        default: all
        type: choice
        options:
          - all
          - smoke
          - regression

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      PASSWORD: ${{ secrets.PASSWORD }}
      SHORT_PASSWORD: ${{ secrets.SHORT_PASSWORD }}
      INVALIDATE_PASSWORD: ${{ secrets.INVALIDATE_PASSWORD }}
      WRONG_PASSWORD: ${{ secrets.WRONG_PASSWORD }}

    strategy:
      matrix:
        java: [17, 21]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: maven

      - name: Run all tests
        if: github.event_name == 'push' || github.event_name == 'schedule' || inputs.suite == 'all' || github.event_name == 'pull_request'
        run: mvn clean test

      - name: Run tagged tests
        if: inputs.suite == 'smoke' || inputs.suite == 'regression'
        run: mvn clean test -Dgroups=${{ inputs.suite }}

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: surefire-reports-java-${{ matrix.java }}
          path: target/surefire-reports/

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: allure-results-java-${{ matrix.java }}
          path: allure-results/

  selenium-allure-report:
    name: Generate Selenium Allure Report
    runs-on: ubuntu-latest
    needs: test
    if: always()

    steps:
      - name: Download Selenium Allure results
        uses: actions/download-artifact@v6
        with:
          pattern: allure-results-java-*
          path: allure-results
          merge-multiple: true

      - name: Show Allure results
        run: |
          echo "===== SELENIUM ALLURE RESULTS ====="
          find allure-results -type f

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Install Allure CLI
        run: |
          curl -Lo allure.tgz https://github.com/allure-framework/allure2/releases/download/2.34.1/allure-2.34.1.tgz
          tar -xzf allure.tgz

      - name: Generate Selenium Allure Report
        run: |
          ./allure-2.34.1/bin/allure generate allure-results --clean -o selenium-allure-report

      - name: Upload Selenium Allure Report
        uses: actions/upload-artifact@v6
        with:
          name: selenium-allure-report
          path: selenium-allure-report/